name: lisa
channels:
  - conda-forge
dependencies:
  - python=3.8.18
  - mpi4py=3.1.4
  - mpich=3.3.2
  - numpy=1.24.3
  - matplotlib=3.7.2
  - multiprocess=0.70.15
  - scipy=1.5.3
  - yaml=0.2.5
  - h5py=3.1.0
  - pymultinest=2.12
  - ultranest=3.6.4
  - dynesty=2.1.2
  - dnest4=0.2.4
  - emcee=3.1.4
