name: lisa
channels:
  - conda-forge
dependencies:
  - mpi4py=3.0.3
  - mpich=3.3.2
  - cython=0.29.5
  - matplotlib=3.0.2
  - numpy=1.16.2
  - python=3.7.2
  - yaml=0.1.7
  - h5py=2.10.0
  - multinest
  - pymultinest
  - ultranest
